import type { CartaWiki, EventoBono } from '../tipos';

export const CATALOGO_CARTAS_WIKI: CartaWiki[] = [
  {
    id: 'sk',
    nombre: 'Skull King',
    modo: 'Juego Base',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/skull_king.png',
    habilidad: 'Vence a todos los piratas. Otorga +30 pts por cada pirata capturado en la baza.',
    ganaContra: 'Todos los números, todos los Piratas y Primer Oficial Kong',
    pierdeContra: 'Sirenas',
    bonificacion: '+30 pts por Pirata capturado',
    descripcion: 'El rey de los mares. Vence a todo el mundo pero es seducido ante el canto de las Sirenas.',
  },
  {
    id: 'kong',
    nombre: 'Primer Oficial Kong',
    modo: 'Expansión',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/primer_oficial_kong.png',
    habilidad: 'Gana a piratas normales. Pierde contra Sirena y Skull King. Si gana una baza, copia las habilidades de los piratas capturados.',
    ganaContra: 'Todos los números y Piratas estándar',
    pierdeContra: 'Sirenas y Skull King',
    bonificacion: '+30 pts si es capturado por Skull King o Sirena',
    descripcion: 'Jerarquía pirata superior. Al ganar la mano imita y copia las habilidades de los piratas derrotados.',
  },
  {
    id: 'sirena',
    nombre: 'Sirenas',
    modo: 'Juego Base',
    cantidad: '2 cartas',
    imagen: 'archivos/cartas/sirena.png',
    habilidad: 'Su canto hechiza y derrota al Skull King (+40 pts de bono).',
    ganaContra: 'Todos los números, Monstruos y el Skull King',
    pierdeContra: 'Cualquier Pirata (salvo Primer Oficial Kong)',
    bonificacion: '+40 pts si captura al Skull King',
    descripcion: 'Hechizan al Skull King. Si un Pirata captura una Sirena, se lleva +20 pts.',
  },
  {
    id: 'pirata_brent',
    nombre: 'Bandido Brent',
    modo: 'Juego Base',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/pirata_bandido_bendt.png',
    habilidad: 'Roba dos cartas del mazo. Luego descarta dos cartas de su mano.',
    ganaContra: 'Todos los números y Sirenas',
    pierdeContra: 'Skull King y Piratas jugados antes que él',
    bonificacion: '+20 pts si captura una Sirena',
    descripcion: 'Permite mejorar tu mano robando dos cartas frescas y descartando dos no deseadas.',
  },
  {
    id: 'pirata_rascal',
    nombre: 'Bribón de Roatán',
    modo: 'Juego Base',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/pirata_bribon_de_roatan.png',
    habilidad: 'Permite realizar un envite adicional: 0, 10 o 20 puntos. Si acierta su apuesta de bazas, suma esos puntos.',
    ganaContra: 'Todos los números y Sirenas',
    pierdeContra: 'Skull King y Piratas jugados antes que él',
    bonificacion: '+20 pts si captura una Sirena',
    descripcion: 'El pirata astuto. Te permite arriesgar puntos adicionales sobre el resultado exacto de tu ronda.',
  },
  {
    id: 'pirata_harry',
    nombre: 'Harry el Gigante',
    modo: 'Juego Base',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/pirata_harry_el_gigante.png',
    habilidad: 'Al finalizar la ronda puede modificar su apuesta en ±1 baza.',
    ganaContra: 'Todos los números y Sirenas',
    pierdeContra: 'Skull King y Piratas jugados antes que él',
    bonificacion: '+20 pts si captura una Sirena',
    descripcion: 'Un gigante del mar que te otorga flexibilidad para ajustar tu apuesta inicial de bazas.',
  },
  {
    id: 'pirata_juanita',
    nombre: 'Juanita Jade',
    modo: 'Juego Base',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/pirata_juanita_jade.png',
    habilidad: 'Puede mirar las cartas no repartidas.',
    ganaContra: 'Todos los números y Sirenas',
    pierdeContra: 'Skull King y Piratas jugados antes que ella',
    bonificacion: '+20 pts si captura una Sirena',
    descripcion: 'Te permite inspeccionar en secreto el mazo de cartas que no entraron en juego.',
  },
  {
    id: 'pirata_rosie',
    nombre: 'Rosie de Laney',
    modo: 'Juego Base',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/pirata_rosie_de_laney.png',
    habilidad: 'Elige qué jugador abrirá la siguiente baza.',
    ganaContra: 'Todos los números y Sirenas',
    pierdeContra: 'Skull King y Piratas jugados antes que ella',
    bonificacion: '+20 pts si captura una Sirena',
    descripcion: 'Al ganar la baza, el jugador selecciona quién liderará la siguiente mano.',
  },
  {
    id: 'pirata_tigresa',
    nombre: 'La Tigresa',
    modo: 'Juego Base',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/pirata_tigresa.png',
    habilidad: 'Al jugarla, elegís si actúa como Pirata estándar o como Bandera de Huida (0).',
    ganaContra: 'Todos los números y Sirenas (si se juega como Pirata)',
    pierdeContra: 'Skull King (o contra todas si se juega como Huida)',
    bonificacion: '+20 pts si captura una Sirena',
    descripcion: 'Comodín dual que te permite atacar como Pirata o huir para evitar ganar la baza.',
  },
  {
    id: 'mary_thorne',
    nombre: 'Mary Thorne',
    modo: 'Expansión',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/pirata_mary_thorne.png',
    habilidad: 'Al ganar una baza, elige una posición de carta de la mano de un rival para forzar su jugada.',
    ganaContra: 'Todos los números y Sirenas',
    pierdeContra: 'Skull King y Piratas jugados antes que ella',
    bonificacion: '+20 pts si captura una Sirena',
    descripcion: 'Pirata intrépida que te permite forzar la jugada de una carta al azar en el siguiente turno.',
  },
  {
    id: 'palo_negro',
    nombre: 'Palo Negro / Calavera (El Triunfo)',
    modo: 'Juego Base',
    cantidad: '14 cartas',
    imagen: 'archivos/cartas/palo_negro.png',
    habilidad: 'Palo de Triunfo absoluto entre los números. El 14 Negro otorga +20 pts.',
    ganaContra: 'Cualquier carta Verde, Amarilla o Violeta y Mono 15',
    pierdeContra: 'Sirenas, Piratas y Skull King',
    bonificacion: '+20 pts al capturar el 14 Negro',
    descripcion: 'Triunfo del juego. Un 1 Negro le gana a cualquier 14 de color estándar.',
  },
  {
    id: 'monito15',
    nombre: 'Mono Comodín (15)',
    modo: 'Expansión',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/mono_15.png',
    habilidad: 'Comodín numérico de valor 15 para colores estándar. Pierde contra Palo Negro.',
    ganaContra: 'Cualquier carta 14 de colores normales',
    pierdeContra: 'Palo Negro (Triunfo), Sirenas, Piratas y Skull King',
    bonificacion: 'Sin bono adicional',
    descripcion: 'El número más alto de los colores estándar, pero vulnerable ante el Triunfo.',
  },
  {
    id: 'palo_amarillo',
    nombre: 'Palo Amarillo (1 al 14)',
    modo: 'Juego Base',
    cantidad: '14 cartas',
    imagen: 'archivos/cartas/palo_amarillo.png',
    habilidad: 'Sigue el palo de salida. El 14 Amarillo otorga +10 pts al ser capturado.',
    ganaContra: 'Cartas amarillas de menor valor',
    pierdeContra: 'Cartas amarillas más altas, Palo Negro, Sirenas, Piratas y Skull King',
    bonificacion: '+10 pts al capturar el 14',
    descripcion: 'Palo de color estándar.',
  },
  {
    id: 'palo_violeta',
    nombre: 'Palo Violeta (1 al 14)',
    modo: 'Juego Base',
    cantidad: '14 cartas',
    imagen: 'archivos/cartas/palo_violeta.png',
    habilidad: 'Sigue el palo de salida. El 14 Violeta otorga +10 pts al ser capturado.',
    ganaContra: 'Cartas violetas de menor valor',
    pierdeContra: 'Cartas violetas más altas, Palo Negro, Sirenas, Piratas y Skull King',
    bonificacion: '+10 pts al capturar el 14',
    descripcion: 'Palo de color estándar.',
  },
  {
    id: 'palo_verde',
    nombre: 'Palo Verde (1 al 14)',
    modo: 'Juego Base',
    cantidad: '14 cartas',
    imagen: 'archivos/cartas/palo_verde.png',
    habilidad: 'Sigue el palo de salida. El 14 Verde otorga +10 pts al ser capturado.',
    ganaContra: 'Cartas verdes de menor valor',
    pierdeContra: 'Cartas verdes más altas, Palo Negro, Sirenas, Piratas y Skull King',
    bonificacion: '+10 pts al capturar el 14',
    descripcion: 'Palo de color estándar.',
  },
  {
    id: 'kraken',
    nombre: 'Kraken',
    modo: 'Reglas Avanzadas',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/kraken.png',
    habilidad: 'Monstruo Marino que destruye completamente la baza: nadie la gana.',
    ganaContra: 'Destruye la baza completa',
    pierdeContra: 'Davy Jones o monstruo posterior',
    bonificacion: 'Sin bono adicional',
    descripcion: 'Monstruo supremo que anula la baza en juego.',
  },
  {
    id: 'ballena',
    nombre: 'Ballena Blanca',
    modo: 'Reglas Avanzadas',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/ballena.png',
    habilidad: 'Anula poderes especiales y triunfos: gana el número más alto sin importar color.',
    ganaContra: 'Anula poderes especiales y palos en la baza',
    pierdeContra: 'Davy Jones o monstruo posterior',
    bonificacion: 'Sin bono adicional',
    descripcion: 'Anula poderes especiales y colores en la baza.',
  },
  {
    id: 'raya_moteada',
    nombre: 'Mantarraya Moteada',
    modo: 'Expansión',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/mantarraya_moteada.png',
    habilidad: 'Invierte el orden: la carta numérica más baja gana la baza.',
    ganaContra: 'Hace que la carta más baja gane',
    pierdeContra: 'Davy Jones o monstruo posterior',
    bonificacion: 'Sin bono adicional',
    descripcion: 'Monstruo que invierte la jerarquía numérica.',
  },
  {
    id: 'davy_jones',
    nombre: 'Davy Jones',
    modo: 'Expansión',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/davy_jones.png',
    habilidad: 'Destruye monstruos marinos de la baza. Otorga +20 pts por cada monstruo destruido.',
    ganaContra: 'No gana bazas numéricamente',
    pierdeContra: 'Su función es destruir monstruos marinos',
    bonificacion: '+20 pts por cada Monstruo Marino destruido',
    descripcion: 'Cazador implacable de monstruos marinos.',
  },
  {
    id: 'tablon',
    nombre: 'Caminar por la Tabla',
    modo: 'Expansión',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/caminar_por_la_tabla.png',
    habilidad: 'Elimina un pirata estándar de la baza.',
    ganaContra: 'No gana bazas',
    pierdeContra: 'Pierde contra cualquier carta',
    bonificacion: 'Sin bono adicional',
    descripcion: 'Carta que expulsa a un pirata normal de la disputa.',
  },
  {
    id: 'last_volley',
    nombre: 'La Última Descarga',
    modo: 'Expansión',
    cantidad: '1 carta',
    imagen: 'archivos/cartas/canon.png',
    habilidad: 'Permite jugar una segunda carta y saltarse la última baza (no sirve como huida).',
    ganaContra: 'No gana bazas',
    pierdeContra: 'Pierde contra cualquier carta',
    bonificacion: 'Sin bono adicional',
    descripcion: 'Permite jugar una segunda carta al final de la baza.',
  },
  {
    id: 'botin',
    nombre: 'Botín',
    modo: 'Reglas Avanzadas',
    cantidad: '2 cartas',
    imagen: 'archivos/cartas/botin.png',
    habilidad: 'Crea una alianza. Si ambos aliados aciertan su envite, cobran +20 pts cada uno.',
    ganaContra: 'No gana bazas (Vale 0)',
    pierdeContra: 'Pierde contra cualquier carta',
    bonificacion: '+20 pts a cada aliado si ambos cumplen su apuesta',
    descripcion: 'Carta de alianza pacífica entre dos jugadores.',
  },
  {
    id: 'huida',
    nombre: 'Huida',
    modo: 'Juego Base',
    cantidad: '5 cartas',
    imagen: 'archivos/cartas/huida.png',
    habilidad: 'Pierde frente a cualquier otra carta. Útil para evitar ganar bazas no deseadas.',
    ganaContra: 'Ninguna carta.',
    pierdeContra: 'Todas las cartas.',
    bonificacion: 'Sin bonificación.',
    descripcion: 'Permite descartarse sin competir por la victoria de la mano.',
  },
  {
    id: 'carta_blanca_base',
    nombre: 'Carta Blanca (Comodín de Bonificación)',
    modo: 'Reglas Avanzadas',
    cantidad: '4 cartas (u 8 con expansión)',
    imagen: 'archivos/cartas/carta_blanca.png',
    habilidad: 'Se aparta al recibirla y se roba otra carta. Otorga bonificación acumulada al final.',
    ganaContra: 'No se juega en las bazas',
    pierdeContra: 'No se juega en las bazas',
    bonificacion: '1 = +5 pts | 2 = +10 pts | 3 = +20 pts | 4+ = +50 pts al final',
    descripcion: 'Comodín de bonificación acumulativo.',
  },
];

export const LISTA_EVENTOS_BONO: EventoBono[] = [
  { id: 'pirata_por_sk', etiqueta: 'Pirata capturado por Skull King (+30 c/u)', puntos: 30, maximo: 7 },
  { id: 'sk_por_sirena', etiqueta: 'Skull King capturado por Sirena (+40 c/u)', puntos: 40, maximo: 1 },
  { id: 'sirena_por_pirata', etiqueta: 'Sirena capturada por Pirata (+20 c/u)', puntos: 20, maximo: 2 },
  { id: 'catorce_negro', etiqueta: '14 Negro / Triunfo (+20 c/u)', puntos: 20, maximo: 1 },
  { id: 'catorce_color', etiqueta: '14 de Color (+10 c/u)', puntos: 10, maximo: 3 },
  { id: 'ocho_expansion', etiqueta: '8 capturado (+5 pts c/u)', puntos: 5, maximo: 4 },
  { id: 'siete_expansion', etiqueta: '7 capturado (-5 pts c/u)', puntos: -5, maximo: 4 },
  { id: 'alianza_botin', etiqueta: 'Alianza de Botín (+20 c/u)', puntos: 20, maximo: 2 },
  { id: 'monstruo_davy', etiqueta: 'Monstruo destruido por Davy Jones (+20 c/u)', puntos: 20, maximo: 3 },
  { id: 'kong_por_sk_sirena', etiqueta: 'Primer Oficial Kong capturado por SK/Sirena (+30)', puntos: 30, maximo: 1 },
];
